export const AWAIT_RESULTS = "AwaitResults";
export const CHOOSE_ROLE = "ChooseRole";
export const CONNECT_WALLET = "ConnectWallet";
export const DONE = "Done";
export const FUND_ACCOUNT = "FundAccount";
export const GET_GUESS ='GetGuess';
export const GET_SEED = 'GetSeed';
export const TIMEOUT = "Timeout";
export const WRAPPER = "Wrapper";